### ISSUE TITLE
A warning near html5 type

### ISSUE THREAD

**Issue by ProgrammingLife** [ts-defold/types#6]
I use following code in TS-Defold:
```typescript
if ( html5 ) {
}
```
And near such lines I get very annoying warnings:
```
warning TSTL: Only false and nil evaluate to 'false' in Lua, everything else is considered 'true'. Explicitly compare the value with ===.

32  if ( html5 ) {
```

I see html5 declared as a namespace in types so indeed it can't return any value. So what can I do to get rid of this warning?

**Comment by thinknathan** [comment]
The transpiler is warning you against relying on [Boolean coercion](https://typescripttolua.github.io/docs/caveats#boolean-coercion) because it doesn't work the same way between TypeScript and Lua. Explicitly compare against undefined instead.

```ts
if (html5 !== undefined) {
}
```

Feel free to visit the Discord if you have similar questions in future.
